# Generated by Django 3.1.3 on 2021-04-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210422_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='expire_date',
        ),
    ]
