# Generated by Django 3.1.3 on 2021-04-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210422_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='availability',
        ),
    ]
