# Generated by Django 3.1.3 on 2021-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_tool_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Deactive'), (1, 'Active')], default=1),
        ),
    ]
