# Generated by Django 3.1.3 on 2021-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210424_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtool',
            name='release',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='borrowtool',
            name='release_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
